[package]
name = "executor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
extreme = "666.666.666666"
mio = { version = "0.8.10", features = [ "net", "os-poll" ] }
